-- MySQL Script generated by MySQL Workbench
-- Fri Jul  5 20:24:15 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ligmogi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ligmogi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ligmogi` DEFAULT CHARACTER SET utf8 ;
USE `ligmogi` ;

-- -----------------------------------------------------
-- Table `ligmogi`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ligmogi`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ligmogi`.`comercios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ligmogi`.`comercios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `site` VARCHAR(45) NULL,
  `resumo` MEDIUMTEXT NULL,
  `wpp` VARCHAR(45) NULL,
  `facebook` VARCHAR(45) NULL,
  `atividade` VARCHAR(120) NULL,
  `capa` TINYINT NOT NULL,
  `icone` MEDIUMTEXT NULL,
  `banner` MEDIUMTEXT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ligmogi`.`enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ligmogi`.`enderecos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `comercios_id` INT NOT NULL,
  `rua` VARCHAR(90) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(45) NOT NULL,
  `complemento` VARCHAR(45) NULL,
  `latitude` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `enderecoscol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_table1_comercios_idx` (`comercios_id` ASC),
  CONSTRAINT `fk_table1_comercios`
    FOREIGN KEY (`comercios_id`)
    REFERENCES `ligmogi`.`comercios` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ligmogi`.`relefones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ligmogi`.`relefones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `comercios_id` INT NOT NULL,
  `telefone` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_relefones_comercios1_idx` (`comercios_id` ASC),
  CONSTRAINT `fk_relefones_comercios1`
    FOREIGN KEY (`comercios_id`)
    REFERENCES `ligmogi`.`comercios` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ligmogi`.`horarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ligmogi`.`horarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `comercios_id` INT NOT NULL,
  `seg` VARCHAR(45) NOT NULL,
  `ter` VARCHAR(45) NOT NULL,
  `quar` VARCHAR(45) NOT NULL,
  `quin` VARCHAR(45) NOT NULL,
  `sex` VARCHAR(45) NOT NULL,
  `sab` VARCHAR(45) NOT NULL,
  `dom` VARCHAR(45) NOT NULL,
  `feriado` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_horarios_comercios1_idx` (`comercios_id` ASC),
  CONSTRAINT `fk_horarios_comercios1`
    FOREIGN KEY (`comercios_id`)
    REFERENCES `ligmogi`.`comercios` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
